"""phase6_rules_risk_alerts

Revision ID: 40f229aa162b
Revises: 43d29daf2fbd
Create Date: 2026-09-09 20:49:47.353176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f229aa162b'
down_revision: Union[str, Sequence[str], None] = '43d29daf2fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_parameter_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sensor_type', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threshold_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threshold_rules_sensor_type'), ['sensor_type'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('condition_key', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['integrated_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_condition_key'), ['condition_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['integrated_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_assessed_at'), ['assessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_risk_level'), ['risk_level'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_risk_level'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_node_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_assessed_at'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_node_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_condition_key'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('threshold_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threshold_rules_sensor_type'))

    op.drop_table('threshold_rules')
    op.drop_table('multi_parameter_rules')
    # ### end Alembic commands ###
