"""Initial schema: mines, zones, nodes, sensors, sensor_readings

Revision ID: 43d29daf2fbd
Revises: 
Create Date: 2026-09-09 18:00:57.530884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d29daf2fbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mines_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_mines_name'), ['name'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_mine_id'), ['mine_id'], unique=False)

    op.create_table('integrated_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('node_identifier', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrated_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrated_nodes_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrated_nodes_node_identifier'), ['node_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_integrated_nodes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrated_nodes_zone_id'), ['zone_id'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=64), nullable=False),
    sa.Column('sensor_identifier', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['integrated_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_sensor_type'), ['sensor_type'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['integrated_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_readings_node_id'), ['node_id'], unique=False)
        batch_op.create_index('ix_sensor_readings_node_timestamp', ['node_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index('ix_sensor_readings_sensor_timestamp', ['sensor_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_readings_timestamp'))
        batch_op.drop_index('ix_sensor_readings_sensor_timestamp')
        batch_op.drop_index(batch_op.f('ix_sensor_readings_sensor_id'))
        batch_op.drop_index('ix_sensor_readings_node_timestamp')
        batch_op.drop_index(batch_op.f('ix_sensor_readings_node_id'))

    op.drop_table('sensor_readings')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_sensor_type'))
        batch_op.drop_index(batch_op.f('ix_sensors_node_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('integrated_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrated_nodes_zone_id'))
        batch_op.drop_index(batch_op.f('ix_integrated_nodes_status'))
        batch_op.drop_index(batch_op.f('ix_integrated_nodes_node_identifier'))
        batch_op.drop_index(batch_op.f('ix_integrated_nodes_last_seen_at'))

    op.drop_table('integrated_nodes')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_mine_id'))
        batch_op.drop_index(batch_op.f('ix_zones_code'))

    op.drop_table('zones')
    with op.batch_alter_table('mines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mines_name'))
        batch_op.drop_index(batch_op.f('ix_mines_code'))

    op.drop_table('mines')
    # ### end Alembic commands ###
