"""phase7_ai_anomalies

Revision ID: 4463c79c1f55
Revises: 40f229aa162b
Create Date: 2026-09-09 21:01:13.543028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4463c79c1f55'
down_revision: Union[str, Sequence[str], None] = '40f229aa162b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=64), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['integrated_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_anomalies_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_anomalies_is_anomaly'), ['is_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_anomalies_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_anomalies_sensor_type'), ['sensor_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_anomalies_sensor_type'))
        batch_op.drop_index(batch_op.f('ix_ai_anomalies_node_id'))
        batch_op.drop_index(batch_op.f('ix_ai_anomalies_is_anomaly'))
        batch_op.drop_index(batch_op.f('ix_ai_anomalies_detected_at'))

    op.drop_table('ai_anomalies')
    # ### end Alembic commands ###
