/**
 * Alert Adapter
 *
 * Maps backend AlertResponse (2-tier severity: WARNING/CRITICAL, 2-state: ACTIVE/RESOLVED)
 * into frontend MineAlert schema required by the Alerts Center.
 */

import type { AlertCategory, AlertOperationalStatus, AlertSeverityLevel, MineAlert, SensorContributionState } from '../../data/mock/alertsCenter';
import type { DashboardAlert } from '../../data/mock/alerts';
import type { AlertSeverity } from '../../types/safety';
import type { AlertResponse } from '../../types/api';
import { formatRelativeTime } from '../../utils/date';

/**
 * Maps backend alert type to frontend category.
 */
function mapAlertCategory(alertType: string): AlertCategory {
  switch (alertType.toUpperCase()) {
    case 'THRESHOLD':
      return 'GROUND_MOVEMENT';
    case 'MULTI_PARAMETER':
      return 'GROUND_MOVEMENT';
    case 'NODE_UNRESPONSIVE':
      return 'NODE_HEALTH';
    default:
      return 'SENSOR_ANOMALY';
  }
}

/**
 * Maps backend severity ('WARNING' | 'CRITICAL') to frontend AlertSeverityLevel.
 */
function mapAlertSeverity(severity: string): AlertSeverityLevel {
  const upper = severity.toUpperCase();
  if (upper === 'CRITICAL') return 'CRITICAL';
  if (upper === 'HIGH_RISK') return 'HIGH_RISK';
  return 'WARNING';
}

/**
 * Maps backend status ('ACTIVE' | 'RESOLVED') to frontend AlertOperationalStatus.
 */
function mapAlertStatus(status: string): AlertOperationalStatus {
  const upper = status.toUpperCase();
  if (upper === 'RESOLVED') return 'RESOLVED';
  return 'NEW';
}

/**
 * Parses context_data from backend to extract contributing sensor metrics.
 */
function extractContributingSensors(
  contextData?: Record<string, unknown>
): SensorContributionState[] {
  if (!contextData || typeof contextData !== 'object') return [];

  const list: SensorContributionState[] = [];
  for (const [key, val] of Object.entries(contextData)) {
    if (typeof val === 'number' || typeof val === 'string') {
      list.push({
        sensor: key,
        parameter: key.replace(/_/g, ' ').toUpperCase(),
        hardwareDevice: 'Integrated Telemetry Node',
        status: 'Elevated',
        currentVal: String(val),
        baselineVal: 'Nominal',
        deviation: '+Deviation Detected',
        isContributing: true,
      });
    }
  }

  return list;
}

/**
 * Adapts a single backend AlertResponse into a rich MineAlert DTO.
 */
export function adaptAlertResponseToMineAlert(backendAlert: AlertResponse): MineAlert {
  const contributingSensors = extractContributingSensors(backendAlert.context_data);

  return {
    id: `ALT-${backendAlert.id}`,
    timestamp: backendAlert.triggered_at,
    relativeTime: formatRelativeTime(backendAlert.triggered_at),
    duration: formatRelativeTime(backendAlert.triggered_at),
    nodeId: backendAlert.node_identifier,
    zone: 'Monitored Sector',
    panel: 'Active Panel',
    severity: mapAlertSeverity(backendAlert.severity),
    status: mapAlertStatus(backendAlert.status),
    category: mapAlertCategory(backendAlert.alert_type),
    title: backendAlert.condition_key.replace(/_/g, ' '),
    description: backendAlert.message,
    riskScore: backendAlert.severity.toUpperCase() === 'CRITICAL' ? 85 : 55,
    riskTrend: 'Stable',
    confidencePct: 90,
    contributingSensors,
    contributingCount: contributingSensors.length,
    totalSensorsCount: Math.max(contributingSensors.length, 6),
    spatialCorrelation: {
      nearbyNodes: [],
      nodeStatuses: [],
      clusterSummary: 'Single-node telemetry event',
    },
    temporalProgression: [
      {
        time: backendAlert.triggered_at,
        parameter: backendAlert.condition_key,
        description: backendAlert.message,
      },
    ],
    recommendedAction: backendAlert.severity.toUpperCase() === 'CRITICAL'
      ? 'Immediate geotechnical visual inspection and TARP Level 3 review.'
      : 'Review sensor trends and verify node battery / communication health.',
    escalationHistory: [
      {
        time: backendAlert.triggered_at,
        severity: mapAlertSeverity(backendAlert.severity),
        label: `Alert Triggered: ${backendAlert.condition_key}`,
      },
    ],
    auditHistory: [
      {
        time: backendAlert.created_at,
        action: 'Alert Generated by Safety Engine',
        actor: 'System Daemon',
      },
      ...(backendAlert.resolved_at
        ? [
            {
              time: backendAlert.resolved_at,
              action: 'Alert Resolved',
              actor: 'Operator Console',
              notes: (backendAlert.context_data?.resolution_note as string) || undefined,
            },
          ]
        : []),
    ],
    resolvedAt: backendAlert.resolved_at || undefined,
  };
}

/**
 * Adapts a backend AlertResponse into a DashboardAlert for dashboard widgets.
 */
export function adaptAlertResponseToDashboardAlert(backendAlert: AlertResponse): DashboardAlert {
  const sev = backendAlert.severity.toLowerCase();
  const mappedSev: AlertSeverity = sev === 'critical' ? 'critical' : 'warning';

  return {
    id: `ALT-${backendAlert.id}`,
    severity: mappedSev,
    target: `Node ${backendAlert.node_identifier}`,
    nodeId: backendAlert.node_identifier,
    description: backendAlert.message,
    timestamp: formatRelativeTime(backendAlert.triggered_at),
    isAcknowledged: backendAlert.status.toUpperCase() === 'RESOLVED',
  };
}
