"""Synthetic Demonstration Data Seeder for SIH 2026 Mine Safety Backend.

Phase 10 Scope: Populates a local or target database with a realistic
demonstration mine facility hierarchy, multimodal sensor suites, prototype
safety rules, and initial historical telemetry.

CRITICAL NOTICE:
All records generated by this script are SYNTHETIC DEMONSTRATION DATA
created exclusively for prototype execution and evaluation.
They do NOT represent certified sensor values, statutory safety thresholds,
or real-world mine conditions.
"""

import asyncio
from datetime import datetime, timezone, timedelta
import sys
from pathlib import Path

# Add project root to sys.path so script can be run directly
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from sqlalchemy import select
from backend.app.db.base import Base
from backend.app.db.session import AsyncSessionLocal, engine
from backend.app.models import (
    IntegratedNode,
    Mine,
    MultiParameterRule,
    Sensor,
    SensorReading,
    ThresholdRule,
    Zone,
)


async def seed_data() -> None:
    """Populate the database with structured demonstration entities."""
    print("=" * 70)
    print("SIH 2026 Integrated Mine Safety Monitoring System")
    print("SYNTHETIC DEMO DATA SEEDER")
    print("=" * 70)
    print("NOTICE: All sensor values and thresholds are purely synthetic demo data.\n")

    # Ensure tables exist
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        # Check if already seeded
        existing_mines = await session.execute(select(Mine))
        if existing_mines.scalars().first():
            print("Database already contains facility data. Skipping duplicate seed.")
            return

        now = datetime.now(timezone.utc)

        # 1. Monitored Mine Facilities
        mine1 = Mine(name="Jharia Deep Colliery No. 5", code="JHR-05")
        mine2 = Mine(name="Raniganj East Shaft Facility", code="RNJ-01")
        session.add_all([mine1, mine2])
        await session.flush()
        print(f"[+] Created 2 Mine facilities: {mine1.name}, {mine2.name}")

        # 2. Operational Zones
        zone_a = Zone(mine_id=mine1.id, name="Main Extraction Gallery North", code="ZONE-A")
        zone_b = Zone(mine_id=mine1.id, name="Central Ventilation Return Shaft", code="ZONE-B")
        zone_c = Zone(mine_id=mine1.id, name="Haulage Incline Sub-level 3", code="ZONE-C")
        zone_d = Zone(mine_id=mine2.id, name="Deep Seam Face 2", code="ZONE-D")
        session.add_all([zone_a, zone_b, zone_c, zone_d])
        await session.flush()
        print("[+] Created 4 Operational Zones (Zone A, Zone B, Zone C, Zone D)")

        # 3. Integrated Nodes
        # Node 1: Active in Zone A
        node1 = IntegratedNode(
            zone_id=zone_a.id,
            node_identifier="NODE-JHR-01",
            status="ACTIVE",
            last_seen_at=now,
        )
        # Node 2: Active in Zone B
        node2 = IntegratedNode(
            zone_id=zone_b.id,
            node_identifier="NODE-JHR-02",
            status="ACTIVE",
            last_seen_at=now,
        )
        # Node 3: Unresponsive in Zone C (demonstration of watchdog alert)
        node3 = IntegratedNode(
            zone_id=zone_c.id,
            node_identifier="NODE-JHR-03",
            status="ACTIVE",
            last_seen_at=now - timedelta(seconds=180),  # Past 60s timeout
        )
        # Node 4: Active in Zone D
        node4 = IntegratedNode(
            zone_id=zone_d.id,
            node_identifier="NODE-RNJ-01",
            status="ACTIVE",
            last_seen_at=now,
        )
        session.add_all([node1, node2, node3, node4])
        await session.flush()
        print("[+] Registered 4 Integrated Nodes (3 responsive, 1 simulated unresponsive)")

        # 4. Multimodal Sensor Suites
        sensor_configs = [
            ("methane_ch4", "ch4_main", "%"),
            ("carbon_monoxide_co", "co_main", "ppm"),
            ("oxygen_o2", "o2_main", "%"),
            ("temperature", "temp_01", "degC"),
            ("humidity", "humidity_01", "%RH"),
            ("pressure", "baro_01", "hPa"),
            ("displacement", "disp_01", "mm"),
            ("vibration", "vib_01", "mm/s"),
            ("crack_progression", "crack_01", "mm"),
        ]

        sensors_created = []
        for node in [node1, node2, node3, node4]:
            for stype, sident, unit in sensor_configs:
                sensor = Sensor(
                    node_id=node.id,
                    sensor_type=stype,
                    sensor_identifier=sident,
                    unit=unit,
                    is_active=True,
                )
                sensors_created.append(sensor)
                session.add(sensor)

        await session.flush()
        print(f"[+] Mounted {len(sensors_created)} sensors across all 9 multimodal capabilities")

        # 5. Prototype Safety Rules
        th1 = ThresholdRule(
            name="Methane Advisory Level",
            sensor_type="methane_ch4",
            operator="GT",
            threshold_value=1.0,
            severity="WARNING",
            description="SYNTHETIC PROTOTYPE: Advisory notification for elevated methane.",
            is_active=True,
        )
        th2 = ThresholdRule(
            name="Methane Critical Hazard",
            sensor_type="methane_ch4",
            operator="GT",
            threshold_value=2.0,
            severity="CRITICAL",
            description="SYNTHETIC PROTOTYPE: Urgent alert for dangerous methane concentration.",
            is_active=True,
        )
        th3 = ThresholdRule(
            name="Oxygen Deficiency",
            sensor_type="oxygen_o2",
            operator="LT",
            threshold_value=19.5,
            severity="CRITICAL",
            description="SYNTHETIC PROTOTYPE: Oxygen concentration below normal atmospheric safety level.",
            is_active=True,
        )
        session.add_all([th1, th2, th3])

        # Multi-parameter rule
        multi1 = MultiParameterRule(
            name="Compound Gas & Thermal Risk",
            severity="CRITICAL",
            description="SYNTHETIC PROTOTYPE: Correlated elevated methane and ambient heat.",
            is_active=True,
            conditions=[
                {"sensor_type": "methane_ch4", "operator": "GT", "threshold_value": 1.2},
                {"sensor_type": "temperature", "operator": "GT", "threshold_value": 36.0},
            ],
        )
        session.add(multi1)
        await session.flush()
        print("[+] Configured prototype Threshold and Multi-Parameter Correlation Rules")

        # 6. Seed Initial Historical Telemetry
        node1_sensors = [s for s in sensors_created if s.node_id == node1.id]
        methane_sensor = next(s for s in node1_sensors if s.sensor_type == "methane_ch4")
        temp_sensor = next(s for s in node1_sensors if s.sensor_type == "temperature")
        o2_sensor = next(s for s in node1_sensors if s.sensor_type == "oxygen_o2")

        readings = []
        for i in range(12):
            reading_time = now - timedelta(minutes=60 - (i * 5))
            # Seed readings for Node 1
            readings.append(SensorReading(
                sensor_id=methane_sensor.id,
                node_id=node1.id,
                timestamp=reading_time,
                value=0.35 + (i * 0.02),
            ))
            readings.append(SensorReading(
                sensor_id=temp_sensor.id,
                node_id=node1.id,
                timestamp=reading_time,
                value=24.5 + (i * 0.2),
            ))
            readings.append(SensorReading(
                sensor_id=o2_sensor.id,
                node_id=node1.id,
                timestamp=reading_time,
                value=20.9,
            ))

        session.add_all(readings)
        await session.commit()
        print(f"[+] Persisted {len(readings)} synthetic historical telemetry observations")

    print("\n[SUCCESS] Demonstration database seeded successfully!")
    print("Start the backend with: uvicorn backend.app.main:app --reload")


if __name__ == "__main__":
    asyncio.run(seed_data())
